name: Create Release
on:
  pull_request:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies for frontend in frontend folder
        run: npm --prefix ./frontend install ./frontend

      - name: Run create_release.sh
        run: ./create_release.sh
