---
name: CI/CD Pipeline for Frontend
# Controls when the workflow will run
on:
  push:
    branches:
      - development
      - main
      - master
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - development
      - main
      - master
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - run: lsb_release -a
      - run: uname -a
      - name: Check out Repository Code
        uses: actions/checkout@v3
      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: "frontend/.nvmrc"

      - name: Install app node_modules
        run: |
          cd frontend
          npm ci
        env:
          NPM_CONFIG_LOGLEVEL: verbose
      - name: Lint Repository Code
        run: |
          cd frontend
          npm run lint
      - run: git diff --exit-code
  build:
    needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 10

    steps:
      - run: lsb_release -a
      - run: uname -a
      - name: Check out Repository Code
        uses: actions/checkout@v3
      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: "frontend/.nvmrc"

      - name: Install node modules
        run: |
          cd frontend
          npm ci
        env:
          NPM_CONFIG_LOGLEVEL: verbose

      # - name: Cache Streaming Dependencies
      #   uses: awalsh128/cache-apt-pkgs-action@latest
      #   with:
      #     packages: libunwind-dev libudev-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev gstreamer1.0-plugins-good gstreamer1.0-plugins-bad
      #     version: 1.1

      - name: Build Repository Code
        run: |
          cd frontend
          # npm run lint
