---
name: CI/CD Pipeline for System API
# Controls when the workflow will run
on:
  push:
    branches:
      - development
      - main
      - master
      - "[0-9]+.[0-9]+.x"
    paths:
      - "system_api/**"
  pull_request:
    branches:
      - development
      - main
      - master
      - "[0-9]+.[0-9]+.x"
    paths:
      - "system_api/**"
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - run: lsb_release -a
      - run: uname -a
      - name: Check out Repository Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: $(grep -oP 'go \d+\.\d+' system_api/go.mod | awk '{print $2}')
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
